version: "3"

services:
  spring:
    image: unidrive.azurecr.io/backend:v1
    container_name: unidrive-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - spring-boot-laravel-mysql-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://spring:8080/swagger-ui.html"]
      timeout: 20s
      retries: 5

  laravel:
    image: unidrive.azurecr.io/frontend:v1
    container_name: unidrive-frontend
    restart: unless-stopped
    depends_on:
      spring:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - spring-boot-laravel-mysql-network
    volumes:
        - ./unidrive-laravel/:/var/www/html
      
networks:
  spring-boot-laravel-mysql-network:
    driver: bridge