version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: unidrive-database
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=unidrive
      - MYSQL_USER=unidrive
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql:/var/lib/mysql
    networks:
      - spring-boot-laravel-mysql-network
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 5
        
  spring:
    build:
      context: ./unidrive-spring-boot/
      dockerfile: Dockerfile
    container_name: unidrive-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - spring-boot-laravel-mysql-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://spring:8080/swagger-ui.html"]
      timeout: 20s
      retries: 5

  laravel:
    build:
      context: ./unidrive-laravel/
      dockerfile: Dockerfile
    container_name: unidrive-frontend
    restart: unless-stopped
    depends_on:
      spring:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - spring-boot-laravel-mysql-network
    volumes:
        - ./unidrive-laravel/:/var/www/html
      
networks:
  spring-boot-laravel-mysql-network:
    driver: bridge